apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  completions: 10
  parallelism: 2
  activeDeadlineSeconds: 5
  template:
    spec:
      containers:
      - name: hello-con
        image: ubuntu
        command: ["echo", "welcome"]   
        imagePullPolicy: IfNotPresent
      restartPolicy: Never
