apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
spec:
  #backoffLimit: 2
  template:
    spec:
      containers:
      - name: hello-con
        image: ubuntu
        command: ["ls", "/nodir"]   
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure