apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      volumeMounts:
      - name: config-vol
        mountPath: "/mydata"
  volumes:
    - name: config-vol
      configMap:
        name: my-configmap
