#!/bin/bash
apt-get update -y
apt-get upgrade -y
apt-get install apache2 -y
systemctl start apache2
systemctl enable apache2
echo "<h1>Welcome to Amazon Linux <br> My name is $(hostname -f)</h1>" > /var/www/html/index.html