apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: nginx
      env:
        - name: MY_USERNAME
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: user
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsecrets
              key: password
